### ISSUE TITLE
Add .gitignore in the backend directory

### ISSUE THREAD

**Issue by WinterCore** [ELIASyASSER/BlogApp#2]
Things that should be added to the `.gitignore` file 
- Everything inside the `./uploads` folder.
- The `node_modules` folder.

References:
Check [this article](https://dev.to/ritaly/git-lesson-how-to-use-gitignore-and-gitkeep-5edm) for information about how to push ONLY the uploads folder without its contents.

**Comment by ELIASyASSER** [comment]
Awsome
